places = Dict([
    ("New York ", 1),
    ("Los Angeles ", 1),
    ("Chicago ", 1),
    ("Philadelphia ", 1),
    ("San Antonio ", 1),
    ("San Diego ", 1),
    ("San Francisco ", 1),
    ("Boston ", 1),
    ("Seattle ", 1),
    ("Baltimore ", 1),
    ("Washington ", 1),
    ("Long Beach ", 1),
    ("Richmond ", 1),
    ("Oakland ", 1),
    ("Berkeley ", 1),
    ("Orlando ", 1),
    ("Richmond ", 1),
    ("Pasadena ", 1),
    ("Bethlehem ", 1),
    ("Mountain View ", 1),
    ("Santa Clara ", 1),
    ("Palo Alto ", 1),
])
